### ISSUE TITLE
How to fine-tune the SRGAN model

### ISSUE THREAD

**Issue by JustinhoCHN** [zsdonghao/SRGAN#15]
hi @zsdonghao , I trained your SRGAN model for 2 days , when I evaluate the model with DIV2K images, it give pretty good result, but when I use my own image to test it , the result is not so good. So I want to use my own dataset to fine-tune the pre-train SRGAN model, should I freeze some layers and just train the last few layers? What's your suggestion?

**Comment by zsdonghao** [comment]
hi @JustinhoCHN , you don't need to freeze some layers, just train on it ~

**Comment by JustinhoCHN** [comment]
thanks @zsdonghao , I'm training two models , one is using pre-trained model with my own dataset, the another one is training from scratch with my own dataset, I'll check the result 2 days later.
