### ISSUE TITLE
Significance of 2 Models 

### ISSUE THREAD

**Issue by EdwardSmith1884** [zsdonghao/SRGAN#17]
Hi, 
I was wondering why there are two generator and discriminator models available? I see you actually only use one of each in the GAN, however these do not seem to be the models which align most closely with the original SRGAN architecture. 
 Thank you

**Comment by zsdonghao** [comment]
Hi, there is only one generator and discriminator, if you look the code carefully, you can find a `reuse`.
The architecture of generator and training method are exactly the same with the SRGAN paper.

Thank you

**Comment by EdwardSmith1884** [comment]
Ah, sorry I was not clear. I mean why do you have SRGAN_g2 and SRGAN_d2 in models.py? They do not seem to be called anywhere, but seems to be valid architectures as well. Do they perform better then their SRGAN_g and SRGAN_d counterparts and what prompted you to have the two different forms?

**Comment by zsdonghao** [comment]
Hi, yes the other models haven't been used, if your GPU memory is big, you can try the other discriminator (exactly the same with SRGAN paper), but I find there is not different. For generator, the default one is better.
