### ISSUE TITLE
LR Image preprocessing did not rescale to [0, 1]

### ISSUE THREAD

**Issue by JustinhoCHN** [zsdonghao/SRGAN#19]
In the original paper, the author proposed scaling the LR input images to [0, 1]:
> *We scaled the range of the LR input images to [0, 1] and for the HR images to [−1, 1].*

But in the source code main.py, in the training section line 224, LR input images are rescaled to [-1, 1] instead:
```
for idx in range(0, len(train_hr_imgs), batch_size):
            step_time = time.time()
            b_imgs_384 = tl.prepro.threading_data(
                    train_hr_imgs[idx : idx + batch_size],
                    fn=crop_sub_imgs_fn, is_random=True)
            b_imgs_96 = tl.prepro.threading_data(b_imgs_384, fn=downsample_fn)
``` 
The threading_data function is : 
```
def crop_sub_imgs_fn(x, is_random=True):
    x = crop(x, wrg=384, hrg=384, is_random=is_random)
    x = x / (255. / 2.)
    x = x - 1.
    return x

def downsample_fn(x):
    # We obtained the LR images by downsampling the HR images using bicubic kernel with downsampling factor r = 4.
    x = imresize(x, size=[96, 96], interp='bicubic', mode=None)
    x = x / (255. / 2.)
    x = x - 1.
    return x
```
It seems both the HR images and LR images are rescaled to [-1, 1], if we follow the paper's advice, rescaling the LR images to [0, 1], would it be much better?

**Comment by zsdonghao** [comment]
It doesn't matter, they should have the same performance, but if you want to compute PSNR, you should rescale it to [0, 1].
