### ISSUE TITLE
training on 4K image (3840x2160)

### ISSUE THREAD

**Issue by kankur** [zsdonghao/SRGAN#22]
I am getting following error while training my 4K image dataset
ValueError: Cannot feed value of shape (10, 96, 96, 3) for Tensor 't_image_input_to_SRGAN_generator:0', which has shape '(16, 96, 96, 3)'

**Comment by zsdonghao** [comment]
Just like the error say: the data you feed into the placeholder didn't have the correct shape, you batch size is mismatched.
