### ISSUE TITLE
ValueError: could not broadcast input array from shape (2040,1356,3) into shape (2040)

### ISSUE THREAD

**Issue by luckyboysmith** [zsdonghao/SRGAN#28]
i'm new to GAN, 
i set batchsize form 16 to 4 when training
and when epoch 35, 
this issue occurs:
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    train()
  File "main.py", line 167, in train
    b_imgs = tl.prepro.threading_data(b_imgs_list, fn=get_imgs_fn, path=config.TRAIN.hr_img_path)
  File "/home/wang/SRGAN-master/tensorlayer/prepro.py", line 105, in threading_data
    return np.asarray(results)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (2040,1356,3) into shape (2040)

then how to solve this question?
hope to get your reply!

**Comment by luckyboysmith** [comment]
solved

**Comment by lfang-salk** [comment]
Hey, how did you solve the issue in the end? I am running into exactly the same one. Thank you!!!

**Comment by luckyboysmith** [comment]
@lfang-salk 
sorry to reply so late
i'm too busy these days,,
i meet the problem because i set batchsize to 8, i change the batchsize to 4 and the problem solved.

**Comment by lfang-salk** [comment]
Thank you! @luckyboysmith 

My problem solved too. I ran into the same issue when I set the batchsize to 4 and at the same time modified main.py to fit my GPU's memory (remember there are options within the code saying we can switch to the one better fitting lower memory). When I changed the code back, the problem solved.
