### ISSUE TITLE
issues when training with my own image

### ISSUE THREAD

**Issue by feiyun1265** [zsdonghao/SRGAN#32]
Hi, @zsdonghao, Thank you for sharing your work. I have a problem need you help, thank you!
I occur a error when training with my own image, error information as follows:
Epoch [ 0/100]   28 time: 0.6905s, mse: 0.11056122 
Epoch [ 0/100]   29 time: 0.6591s, mse: 0.09596997 
Epoch [ 0/100]   30 time: 0.6747s, mse: 0.10335217 
Traceback (most recent call last):
  File "main.py", line 316, in <module>
    train()
  File "main.py", line 175, in train
    errM, _ = sess.run([mse_loss, g_optim_init], {t_image: b_imgs_96, t_target_image: b_imgs_384})
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (4, 96, 96, 3) for Tensor 't_image_input_to_SRGAN_generator:0', which has shape '(16, 96, 96, 3)'

**Comment by zsdonghao** [comment]
hi, make sure the data you feed in have the correct batch size ~~

```
ValueError: Cannot feed value of shape (4, 96, 96, 3) for Tensor 't_image_input_to_SRGAN_generator:0', which has shape '(16, 96, 96, 3)'
```

**Comment by animeshramesh** [comment]
@feiyun1265, You need to ensure that the total number of images in your dataset is divisible by the batch size.

**Comment by feiyun1265** [comment]
Thanks for all answer. I have solved the problem. The issuse is the number of training images. Set training images as integral multiple of batch size. Thank you all.
