### ISSUE TITLE
Why do not use low resolution images in training?

### ISSUE THREAD

**Issue by nuli0355** [zsdonghao/SRGAN#39]
First of all, thank you very much for your contribution.
I could not understand Why do not use low resolution images in training, but downsample the resolution of high resolution images?
I'm new. Thank you very much!

**Comment by zsdonghao** [comment]
Hi, the definition of super resolution is to make the image resolution higher.

Low resolution (e.g. float8) to high resolution (e.g. float32) reconstruction may belong to other task?
