### ISSUE TITLE
Please download vgg19.npz from : https://github.com/machrisaa/tensorflow-vgg

### ISSUE THREAD

**Issue by shede1988** [zsdonghao/SRGAN#42]
[!] Load checkpoint/g_srgan.npz failed!
[!] Load checkpoint/g_srgan_init.npz failed!
[!] Load checkpoint/d_srgan.npz failed!
Please download vgg19.npz from : https://github.com/machrisaa/tensorflow-vgg

**Comment by shede1988** [comment]
But I already have vgg19.npy.
What is the difference between vgg19.npy and vgg19.npz

**Comment by zsdonghao** [comment]
hi it is npy, npz is a typo.

**Comment by shede1988** [comment]
Thank you!

**Comment by shede1988** [comment]
How to solve the following error:
Load checkpoint/g_srgan.npz failed!

**Comment by zsdonghao** [comment]
@shede1988 it is not an error, after you train the generator, you will have that npz.
then if you train it again, the code will load the previous model.

**Comment by zzw1123** [comment]
@zsdonghao I wanna know what is the difference between .npy and .npz files?
